// Generates src/components/chat/emoji-data.ts from the Unicode emoji-test.txt
// (version 15.0). Run once when the Unicode version changes, then format:
//
//   node scripts/gen-emoji-data.ts                 (downloads the source)
//   node scripts/gen-emoji-data.ts ./emoji-test.txt (reads a local copy)
//   pnpm exec prettier --write src/components/chat/emoji-data.ts
//
// Keeps fully-qualified emoji only and drops every skin-tone and hair variant,
// so each base emoji appears once. Each entry keeps its glyph, its CLDR short
// name (the search key) and its Unicode group. No emoji library is involved:
// the picker renders the glyphs as text in the app's emoji font stack.

import { get } from 'node:https';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export const UNICODE_VERSION = '15.0';
export const SOURCE_URL = `https://unicode.org/Public/emoji/${UNICODE_VERSION}/emoji-test.txt`;
const OUT = resolve(import.meta.dirname, '../src/components/chat/emoji-data.ts');

/** Skin-tone modifiers (U+1F3FB..U+1F3FF) and hair components (U+1F9B0..U+1F9B3). */
function isVariantCodePoint(cp: number): boolean {
  return (cp >= 0x1f3fb && cp <= 0x1f3ff) || (cp >= 0x1f9b0 && cp <= 0x1f9b3);
}

export interface ParsedEmoji {
  char: string;
  name: string;
  group: string;
}

/** Parse emoji-test.txt: fully-qualified lines only, variants dropped, in file order. */
export function parseEmojiTest(text: string): ParsedEmoji[] {
  const out: ParsedEmoji[] = [];
  let group = '';
  for (const line of text.split('\n')) {
    const groupMatch = /^# group: (.+)$/.exec(line);
    if (groupMatch?.[1] !== undefined) {
      group = groupMatch[1].trim();
      continue;
    }
    if (line.startsWith('#') || line.trim() === '') continue;
    const match = /^([0-9A-F ]+?)\s*;\s*([a-z-]+)\s*#\s*(\S+)\s+E\d+\.\d+\s+(.+)$/.exec(line);
    if (match === null) continue;
    const [, codes, status, char, name] = match;
    if (codes === undefined || status === undefined || char === undefined || name === undefined) {
      continue;
    }
    if (status !== 'fully-qualified' || group === 'Component') continue;
    const points = codes
      .trim()
      .split(/\s+/)
      .map((hex) => parseInt(hex, 16));
    if (points.some(isVariantCodePoint)) continue;
    out.push({ char, name: name.trim(), group });
  }
  return out;
}

function download(url: string): Promise<string> {
  return new Promise((resolvePromise, reject) => {
    get(url, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`GET ${url} returned ${String(res.statusCode)}`));
        res.resume();
        return;
      }
      res.setEncoding('utf8');
      let body = '';
      res.on('data', (chunk: string) => {
        body += chunk;
      });
      res.on('end', () => resolvePromise(body));
    }).on('error', reject);
  });
}

/**
 * A string literal for the generated file. The number sign is written as its
 * escape: src/components/chat bans the raw character (chat-tokens.test.ts).
 */
function literal(value: string): string {
  return JSON.stringify(value).replace(/#/g, '\\u0023');
}

/** The generated module: group names once, then one [glyph, name, group index] row per emoji. */
export function renderModule(emoji: readonly ParsedEmoji[]): string {
  const groups = [...new Set(emoji.map((e) => e.group))];
  const rows = emoji.map(
    (e) => `  [${literal(e.char)}, ${literal(e.name)}, ${groups.indexOf(e.group)}],`,
  );
  return [
    '// GENERATED by scripts/gen-emoji-data.ts. Do not edit by hand.',
    `// Source: Unicode emoji-test.txt, version ${UNICODE_VERSION} (${SOURCE_URL}).`,
    '// Fully-qualified emoji only, no skin-tone or hair variants. Fields: char, name',
    '// (CLDR short name), group (Unicode group).',
    '',
    '/** One pickable emoji. */',
    'export interface EmojiEntry {',
    '  char: string;',
    '  name: string;',
    '  group: string;',
    '}',
    '',
    '/** The Unicode groups, in file order. */',
    `export const EMOJI_GROUPS: readonly string[] = [${groups.map(literal).join(', ')}];`,
    '',
    'const ROWS: readonly (readonly [string, string, number])[] = [',
    ...rows,
    '];',
    '',
    '/** Every pickable emoji, in Unicode order. */',
    'export const EMOJI: readonly EmojiEntry[] = ROWS.map(([char, name, group]) => ({',
    '  char,',
    '  name,',
    "  group: EMOJI_GROUPS[group] ?? '',",
    '}));',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const local = process.argv[2];
  const text = local !== undefined ? readFileSync(local, 'utf8') : await download(SOURCE_URL);
  if (!text.includes(`# Version: ${UNICODE_VERSION}`)) {
    throw new Error(`source is not emoji-test.txt version ${UNICODE_VERSION}`);
  }
  const emoji = parseEmojiTest(text);
  writeFileSync(OUT, renderModule(emoji));
  process.stdout.write(`wrote ${emoji.length} emoji to ${OUT}\n`);
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === import.meta.filename) {
  void main();
}
